### ISSUE TITLE
Syntax highlighting for Scala

### ISSUE THREAD

**Issue by froth** [Genuitec/CodeTogether#137]
**Is your feature request related to a problem? Please describe.**
There is no syntax highlighting for scala.

**Describe the solution you'd like**
Provide syntax highlighting for scala :)

**Describe your primary environment**
Intellij IDEA

**Comment by brianvfernandes** [comment]
Duplicate of #112 
You'll be happy to know this has already been implemented and is coming in version 2.0. Thank you for asking!

**Comment by froth** [comment]
Ah, I did not search closed issues, very nice!
