### ISSUE TITLE
Vim binding support

### ISSUE THREAD

**Issue by AvianAnalyst** [Genuitec/CodeTogether#170]
**Is your feature request related to a problem? Please describe.**
Vim bindings aren't supported in browser, which leads to a great lack of productivity and a lot of frustration when you have the vim muscle memory.

**Describe the solution you'd like**
Vim bindings support being added as an option.

**Describe your primary environment**
IntelliJ, 2-5 participants

**Describe alternatives you've considered**
Being able to connect to a session from a non-host IDE would allow you to leverage that IDE's plugins.

**Comment by toddewilliams** [comment]
This enhancement was added before IDE-to-IDE use was supported.

But now that IDE-to-IDE collaboration is supported, I believe this is now covered. If you want vim bindings, simply install them into your IDE and join the session from your IDE and the bindings will be honored.

I believe this can now be closed as FIXED. @AvianAnalyst do you agree?

**Comment by AvianAnalyst** [comment]
100% agreed. And I think this is a smoother method of implementing it as well
