### ISSUE TITLE
Add support for IntelliJ IDEA 2020.2

### ISSUE THREAD

**Issue by jonasvoelcker** [Genuitec/CodeTogether#174]
Dear CodeTogether-Team,

I would like to suggest adding support for the newest IntelliJ version 2020.2 which recently dropped in.

Unfortunately the plugin is not yet downloadable.

Best Regards
Jonas

**Comment by toddewilliams** [comment]
Jonas, great suggestion. In fact the team has already closed this issue as #169. I'm not sure of the timing of the update for the plugin but it should be relatively soon.

**Comment by jonasvoelcker** [comment]
Hey Tod, nice to hear that. If it is already addressed, there is nothing more to be done :)

**Comment by TimWebb** [comment]
Hi, just confirming that Jetbrains has finished moderation of the plug-in update and is available in their marketplace for 2020.2. In addition, the extension is available on our download page.
