### ISSUE TITLE
Unable to save changes to modified file in VSCode

### ISSUE THREAD

**Issue by jamesmortensen** [Genuitec/CodeTogether#177]
**Describe the bug**
We were in a coding session.  The "guest" attempted to save a JavaScript file, and the file would not save.  There was no error messages, and I didn't see anything typed in my VSCode host window.

**To Reproduce**
1. Start a CodeTogether session.
2. Share url with guest.
3. Guest edits a file and attempts to save.
4. Nothing happens (no error message... nothing)

**Expected behavior**
When clicking save, we expect the file to save.  If it cannot save, we expect there to be some sort of message communicated to us to let us know why.  

**Screenshots**

**CodeTogether Host**
 - IDE: [e.g., VSCode,]
Version: 1.47.2
Commit: 17299e413d5590b14ab0340ea477cdd86ff13daf
Date: 2020-07-15T18:18:50.054Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.0.0

**Browser Participant**
 - Browser: [e.g. Chrome]
 - Browser Version: [e.g. latest]
 - OS: [e.g. Mac OS]
 
**Additional context**

**Workaround (if any)**
To workaround the issue, we had to copy the code in a chat and then me, the host, had to manually integrate it.  Kinda defeated the purpose of using CodeTogether.

**Comment by brianvfernandes** [comment]
James, was the guest coding in "Coding Together" mode? If yes, you should have seen the changes live, even before saving. My guess is that the guest could have gotten disconnected (from CodeTogether, not necessarily the Internet) and that condition was not correctly detected by the browser. _Have you run into this problem more than once?_ 

We are working on improving session reliability for the next release, as well as adding additional monitoring so conditions like this are better detected and reported.

**Comment by wgalanciak** [comment]
Closing this issue as we have not been able to reproduce the issue.
