### ISSUE TITLE
support .gitignore like file for ignore file show on session

### ISSUE THREAD

**Issue by bluelovers** [Genuitec/CodeTogether#179]
**Is your feature request related to a problem? Please describe.**

support .gitignore like file for ignore file show on session

**Describe the solution you'd like**

> .codetogether/.ignore
```
.idea
some file list didn't wanna show for other people
```

**Describe your primary environment**
A clear and concise description of your environment, including host IDE, average number of participants, and roles.

**Describe alternatives you've considered**

**Additional context**

**Comment by brianvfernandes** [comment]
We already support some of this in CodeTogether 2.1, and will be adding support for .gitingore like patterns too. Thank you for asking.

Duplicate of #178
