### ISSUE TITLE
Emacs support

### ISSUE THREAD

**Issue by aaronjensen** [Genuitec/CodeTogether#181]
**Is your feature request related to a problem? Please describe.**
Sure, I don't have a solid way to pair program while using Emacs with someone using VS Code

**Describe the solution you'd like**
It'd be great for CodeTogether to support Emacs

**Describe your primary environment**
Emacs on Linux, typically 1-3 other developers, usually using VS Code, but sometimes using Vim

**Describe alternatives you've considered**
Floobits, just using VS Code and screen sharing over Zoom

**Additional context**
None

**Comment by aaronjensen** [comment]
I didn't realize that editor to editor support doesn't exist right now, so this wouldn't really fit my use case. Going to close this for now as I could join a vs code user via web browser (or just use live share and vs code <> vs code).

**Comment by jsjoeio** [comment]
Can we reopen this? I'm interested in Emacs support

**Comment by norpol** [comment]
Off topic or potentially also some inspiration: There is [`crdt.el`](https://code.librehq.com/qhong/crdt.el/) by Qiantan Hong, I tried it few months ago with a coworker by using `ssh -R` and `ssh -L` onto a shared host. The basic functionality is there, of course not as nice as you'd expect it from other editors but might be worth a shot.
