### ISSUE TITLE
Using Codestream in AndoridStudio leaves all views (Log, Structure, Project View) empty

### ISSUE THREAD

**Issue by Noltibus** [Genuitec/CodeTogether#208]
**Describe the bug**
After the most recent update to CodeTogether (03.11.2020) Android Studio is not usable anymore. All views, like the project view on the left, wont show anything. Instead of listing all my project items and files, it just states "loading...". All other windows, like the log, the CodeTogether View itself are just blank. It is also not possible to open Code files anymore.

**To Reproduce**
1. Activate CodeTogether plugin
2. open existing Android Studio project
3. See nothing

**Expected behavior**
That I see my stuff?!

**CodeTogether Host**
 - IDE: AndroidStudio
 - IDE Version 4.1
 - OS: Windows 
 - OS Version: 10

**Workaround (if any)**
Deactivate CodeTogether plugin

**Comment by wgalanciak** [comment]
Thanks for reporting the issue. We were able to reproduce the issue on our side with CodeStream installed and enabled. We are currently looking at a possible fix.

**Comment by wgalanciak** [comment]
Fix is ready and will be available in the next small update which we are pushing out today. Stay tuned.

**Comment by Noltibus** [comment]
With the newest update, this works again! Thank you very much!
