### ISSUE TITLE
Provide control over permissions including view/follow-only participants

### ISSUE THREAD

**Issue by TimWebb** [Genuitec/CodeTogether#24]
**Describe the solution you'd like**
Provide a way for hosts to decide permission levels of participants including modes like:
- View/follow only participants
- Automatically pre-enable seamless change of control
- Change permissions on a user-by-user basis

**Comment by toddewilliams** [comment]
Simple ability for host to authorize when a collaborator wants to take control was requested separately in this twitter thread: https://twitter.com/brokedba/status/1261428755542638593?s=21
