### ISSUE TITLE
Audio session did not work

### ISSUE THREAD

**Issue by borisovg** [Genuitec/CodeTogether#355]
**Describe the bug**
Audio session did not work - we were able to both join the browser session but neither of us could hear the other on audio.
Also it seems my invitee was unable to unmute / was seeing status as "unmuted" but it wasn't actually so.

**To Reproduce**
1. Start sharing
2. Start audio session
3. Invite another participant
4. Unmute and try to talk

**Expected behavior**
The other side can hear me speak.

**CodeTogether Host**
 - IDE: VSCodium
 - IDE Version: 1.63.0
 - OS:  Ubuntu
 - OS Version: 20.04.3 LTS

**IDE Participant**
 - IDE: VSCode
 - IDE Version: 1.62.1
 - OS: MacOS Big Sur
 - OS Version: 11.5.2

**Browser Host**
 - Browser: Firefox
 - Browser Version: 95

**Browser Participant**
 - Browser: Chrome
 - Browser Version: 96.0.4664.55

**Workaround (if any)**
Use Zoom for audio :)

**Comment by brianvfernandes** [comment]
@borisovg , could you please help us with some WebRTC debugging information to help us track this down and fix? The reason both audio and video are not working for you are very likely related.

**Steps**

1. With Firefox, just before joining A/V, open the `about:webrtc` page and click `Start Debug Mode`
2. Now join A/V, make sure you're unmuted and attempt to talk or share your webcam. 
3. If you click `Show Details` over in the `about:webrtc` page, you should see quite a bit of data being logged. If you don't see data here, please refresh the page. 
4. You can now click, `Stop Debug Mode` and then `Save Page` which will save this data to an HTML file. 

Can you please email this file to support@genuitec.com for further analysis? Thanks!

**Comment by borisovg** [comment]
@brianvfernandes you've got it: I have WebRTC disabled in my browser for security reasons and I forgot about that. Toggling it back on made everything work again. Sorry for the noise.

**Comment by brianvfernandes** [comment]
@borisovg no problem, and thank you for letting us know! We'll try to make "disabled WebRTC" more obvious in product and documentation.
