### ISSUE TITLE
Video did not work

### ISSUE THREAD

**Issue by borisovg** [Genuitec/CodeTogether#356]
**Describe the bug**
Webcam video did not work - browser permission pop up was shown and allowed but the video icon remained crossed out and clicking on it did nothing.

**To Reproduce**
1. Start sharing
2. Start audio session
3. Click the video button

**Expected behavior**
Webcam video should be shown.

**CodeTogether Host**
 - IDE: VSCodium
 - IDE Version: 1.63.0
 - OS:  Ubuntu
 - OS Version: 20.04.3 LTS

**Browser Host**
 - Browser: Firefox
 - Browser Version: 95

**Comment by brianvfernandes** [comment]
For any users experiencing this problem, we would appreciate it if you can send us debugging information using the steps in [this ](https://github.com/Genuitec/CodeTogether/issues/355#issuecomment-993703189)comment.

**Comment by borisovg** [comment]
I have WebRTC disabled in my browser for security reasons and I forgot about that. Toggling it back on made everything work again. Sorry for the noise.
