### ISSUE TITLE
Error requesting session server

### ISSUE THREAD

**Issue by Clemorange22** [Genuitec/CodeTogether#357]
**Describe the bug**
When trying to host a session : 
![image](https://user-images.githubusercontent.com/62897760/146452639-76c6c8b3-4a68-4306-890d-259f9fa58cf7.png)

**To Reproduce**
1. Go to 'Codetogether tab
2. Click on 'Host new session then start
3. See error

**Expected behavior**
Launch collaborating session
**Screenshots**

**CodeTogether Host**
 - IDE: Vscode (code-server)
 - IDE Version : 
 - code-server: v3.11.0
- VS Code: v1.57.1

 - OS: Debian
 - OS Version: 10

**IDE Participant**
Nobody
**Browser Participant**
Nobody
 
**Additional context**
I'm using code-server (self-hosted web vscode)
**Workaround (if any)**
No

**Comment by toddewilliams** [comment]
This is unusual. I note you're using code-server. Did you launch code-server using the flags documented in the [Collaboration Guide](https://coder.com/docs/code-server/latest/collaboration)?

Also, are you behind any sort of a firewall or access the internet through a proxy server? Normally this isn't an issue as CodeTogether uses standard ports, but some configuration might be highly restrictive.

**Comment by Clemorange22** [comment]
I installed code-server via yunohost
Install script is here :
https://github.com/YunoHost-Apps/code-server_ynh
Code server is running behind a nginux proxy
