### ISSUE TITLE
IntelliJ host crashes after starting session

### ISSUE THREAD

**Issue by brianvfernandes** [Genuitec/CodeTogether#367]
We have received a few reports about IntelliJ crashing, or running out of memory after a CodeTogether session is started. A few users have mentioned that this happens for the second session they host - the first one causes no issues in the IDE. 

We have been unable to reproduce this locally, so if you've experienced a similar issue with CodeTogether, please add a comment mentioning the following so we can track it down, thanks!

1. Version of CodeTogether
2. Exact distribution and version of IntelliJ
3. Operating System of the Host
4. Do you experience issues in the first session hosted, or do they only appear for subsequently hosted sessions?

**Comment by eric88** [comment]
I am evaluating CodeTogether and have run into this issue. My information is as follows:
1. Version of CodeTogether: 2022.1.4-01289
2. Exact distribution and version of IntelliJ: IntelliJ IDEA 2021.3.3 (Ultimate Edition) Build #IU-213.7172.25, built on March 15, 2022
3. Operating System of the Host: macOS Big Sur 11.6.4
4. The issue only occurs on subsequently hosted sessions

**Comment by toddewilliams** [comment]
Thank you for the details @eric88. The team may have a few more questions as this one is being very actively investigated and we'll ship a fix for it as soon as we've determined the root cause(s).
