### ISSUE TITLE
403 Forbidden when trying to view dashboard (On-Premise)

### ISSUE THREAD

**Issue by hmkrivoj** [Genuitec/CodeTogether#368]
**Describe the bug**
When trying to access the dashboard by using the dynamically generated credentials in the application log, the access to the dashboard is denied with the error message "403 Forbidden | nginx". 
**To Reproduce**
1. Install Codetogether v2022.1.4-01289 to OpenShift by using Helm-Charts
2. **Don't** configure `CT_DASHBOARD_USER` and `CT_DASHBOARD_PASSWORD`
3. Start application and copy dynamically generated dashboard credentials from application log
4. Use credentials to try to access dashboard
5. See error

**Expected behavior**
I expect to be able to access the dashboard by using the dynamically generated credentials.

**Additional context**
Using any other credentials also results in 403 even though they are invalid.

**Comment by brianvfernandes** [comment]
@hmkrivoj can you please confirm that you're using the latest version of our Helm Chats to deploy, and not something custom? The chart version should be 1.4.2.
Could you also please send us the entire log for the running CodeTogether container? 
Does the page at https://[CTSERVERFQDN]/clients (the CodeTogether plugin/extension download page) load correctly in your browser?

Please send us these details via email at support@genuitec.com and we'll take it from there. Thanks!

**Comment by hmkrivoj** [comment]
I can't reproduce this on 2023.1. Seems to be fixed 👍
