### ISSUE TITLE
Allow guests to identify themselves with a persistent name

### ISSUE THREAD

**Issue by TimWebb** [Genuitec/CodeTogether#4]
Currently session participants are anonymous. We should allow participants to login or at least provide a visible name stored in a browser cookie.

**Comment by txava** [comment]
Now you can  change the name to use as participant by clicking on the participant name(it will be a random animal name if not set) in status bar.
![set-name-screenshot](https://user-images.githubusercontent.com/802075/76256937-5a2e2e80-6216-11ea-8985-4a33bcb9c5dd.png)

This name change will be persisted across browser sessions.
