### ISSUE TITLE
Suggestion - Add participant information to VS Code session

### ISSUE THREAD

**Issue by wpschaub** [Genuitec/CodeTogether#7]
We're missing the following visual information in the Visual Studio Code instance that creates a CodeTogether session:

- Active participants, without starting another browser session that shows participants.
- Active controller. A visual cue on which participants currently controls the session.

**Comment by TimWebb** [comment]
Great feedback! For the upcoming 1.0.5 release, we were actively working on visualizing who is in control right inside the editor, but you are right that we should contribute a view/pane that also covers the participants.

**Comment by TimWebb** [comment]
We've confirmed a design for this coming in 1.0.6 that has a much improved experience across Hosts and Browser which shows who is in control, where other people are browsing and recently modified files.

**Comment by TimWebb** [comment]
Delivered in 1.1.0!
