### ISSUE TITLE
Introduction video available for Hosts

### ISSUE THREAD

**Issue by TimWebb** [Genuitec/CodeTogether#71]
**Describe the solution you'd like**
To help new users understand how to use CodeTogether, we should create a video and integrate it into the welcome text that shows the core of how CodeTogether works, including briefly covering security concerns, how to invite participants, and a brief show of the capabilities available.

This should be made available for optional viewing -- by no means should the video automatically start or be bundled into the product. It can be shown on an embedded or external browser if thumbnail clicked.

**Comment by wgalanciak** [comment]
We are not going to implement this feature.
