### ISSUE TITLE
does not work with eclipse 2020.03

### ISSUE THREAD

**Issue by osdevguy** [Genuitec/CodeTogether#8]
Update site details seem out of date or not working then bombs

**Comment by TimWebb** [comment]
do you get a specific error message?  i'm running locally with 2020.03.  (will do a fresh install to double check)

**Comment by TimWebb** [comment]
FYI - we've just rolled out the 1.0.5 update to CodeTogether. Perhaps with that you can get up and going.

**Comment by osdevguy** [comment]
perfect - its working thanks!!
