### ISSUE TITLE
Allow host connections through common ports

### ISSUE THREAD

**Issue by brianvfernandes** [Genuitec/CodeTogether#90]
**Is your feature request related to a problem? Please describe.**
Cannot start a  CodeTogether session - company firewall blocks non standard ports.

**Describe the solution you'd like**
Would like CodeTogether to allow connections through more standard ports (like 443), at least by means of a configurable setting.

**Describe your primary environment**
Host IDE: IntelliJ IDEA 2020.1.1 (Community Edition)

**Comment by JThoennes** [comment]
@brianvfernandes Thanks for chatting on gitter. Currently, this issue blocks me from evaluating CodeTogether. So it is a show-stopper for me.

**Comment by brianvfernandes** [comment]
@JThoennes understood, thank you for the update. We'll try to take a look at this issue as soon as we wrap up the upcoming release. With some investigation then, we'll have a better idea of the scope of the changes required at our end to support this.

**Comment by JThoennes** [comment]
Since you also offer on-premises support, I wonder how you could do that without changing the host and port to the internal on-premise server. Waiting for your findings, thanks.

**Comment by TimWebb** [comment]
I am happy to report that the server infrastructure has been migrated to run on port 443 for the secure web socket connections instead of non-standard ports like 3001, 3002.
